### ISSUE TITLE
edx & itmoproctor

### ISSUE THREAD

**Issue by lexasub** [openeduITMO/ITMOproctor#14]
Does have ITMOproctor documentation(not install, but using)? 
Can i itegrate ITMOproctor with open edx?

**Comment by avlyubimov** [comment]
Добрый день! У меня вопрос, можно интегрировать вашу систему с moodle?

**Comment by elenacherepovskaya** [comment]
> Does have ITMOproctor documentation(not install, but using)?
> Can i itegrate ITMOproctor with open edx?

Hello! Yes, currently the system is integrated with "Open education" portal, which is based on Open edX. However, our repository provides integration module for our side, but does not contain module for Open edX itself.

**Comment by elenacherepovskaya** [comment]
> Добрый день! У меня вопрос, можно интегрировать вашу систему с moodle?

Добрый день! Возможность интеграции есть, но на текущий момент таких задач не возникало.  Потребуется добавление модуля интеграции с запрашиваемым типом систем. Сейчас система поддерживает интеграцию с Open edX.
